name: PR Approval Hook GHA 
on:
  pull_request:
  
permissions:
  contents: read

jobs:
  gha-custom-hook:
    runs-on: arc1
    steps:
     - name: Harden the runner (Audit all outbound calls)
       uses: step-security/harden-runner@v2
       with:
         egress-policy: audit

     - run: "ls"
     - run: "env"
